name: Update Translations
# Change later for schedules
on:
  push:
    branches:
      - add-gh-actions

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: |
            node_modules

      - name: Install latest npm
        run: |
          npm install -g npm &&
          npm --version &&
          npm list -g --depth 0

      - name: Install packages
        run: npm install

      - name: Test Lint
        run: npm run format-all
